In [10]:
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import numpy as np
import cv2 as cv
import time

def nothing(x):
    pass

# Load the grayscale image
img = cv.imread('Crater (lat and lon).png', cv.IMREAD_GRAYSCALE)
#img = cv.imread('Moon craters.png', cv.IMREAD_GRAYSCALE)
assert img is not None, "File could not be read, check with os.path.exists()"

img = cv.medianBlur(img, 9)
cimg = cv.cvtColor(img, cv.COLOR_GRAY2BGR)

# Create a window and trackbars for parameter adjustment
cv.namedWindow('Circle Detection')
cv.createTrackbar('Param1', 'Circle Detection', 30, 100, nothing)
cv.createTrackbar('Param2', 'Circle Detection', 40, 100, nothing)
cv.createTrackbar('Min Radius', 'Circle Detection', 8, 100, nothing)
cv.createTrackbar('Max Radius', 'Circle Detection', 50, 100, nothing)

while True:
    # Get current positions of trackbars
    param1 = cv.getTrackbarPos('Param1', 'Circle Detection')
    param2 = cv.getTrackbarPos('Param2', 'Circle Detection')
    min_radius = cv.getTrackbarPos('Min Radius', 'Circle Detection')
    max_radius = cv.getTrackbarPos('Max Radius', 'Circle Detection')
    
    # Detect circles
    circles = cv.HoughCircles(img, cv.HOUGH_GRADIENT, 1, 50,
                              param1=param1, param2=param2,
                              minRadius=min_radius, maxRadius=max_radius)
    
    # Make a copy of the image to draw on
    display_img = cimg.copy()
    
    if circles is not None:
        circles = np.uint16(np.around(circles))
        for i in circles[0, :]:
            # Draw the outer circle
            #cv.circle(display_img, (i[0], i[1]), i[2], (0, 255, 0), 2)
            # Draw the center of the circle
            cv.circle(display_img, (i[0], i[1]), 2, (0, 0, 255), 3)
    else:
        print("No circles were found.")

    # Show the result
    #time.sleep(0.1)
    cv.imshow('Circle Detection', display_img)
    
    # Exit if 'q' is pressed
    if cv.waitKey(1) & 0xFF == ord('q'):
        break

cv.destroyAllWindows()
cv.waitKey(1)
#cv.waitKey(0); cv.destroyAllWindows(); cv.waitKey(1)

No circles were found.
No circles were found.
No circles were found.
No circles were found.
No circles were found.
No circles were found.
No circles were found.
No circles were found.
No circles were found.
No circles were found.
No circles were found.
No circles were found.
No circles were found.
No circles were found.
No circles were found.
No circles were found.
No circles were found.
No circles were found.
No circles were found.
No circles were found.
No circles were found.
No circles were found.
No circles were found.
No circles were found.
No circles were found.
No circles were found.
No circles were found.
No circles were found.
No circles were found.
No circles were found.
No circles were found.
No circles were found.
No circles were found.
No circles were found.
No circles were found.
No circles were found.
No circles were found.
No circles were found.
No circles were found.
No circles were found.
No circles were found.
No circles were found.
No circles were found.
No circles 

-1

In [18]:
print(circles.shape)
print(circles)
print(img.shape)

(1, 47, 3)
[[[886 304  39]
  [688 490  42]
  [778 206  42]
  [528 108  26]
  [824 492  33]
  [470 298  29]
  [642 366  30]
  [330 572  22]
  [886 208  49]
  [496 552  32]
  [528 248  27]
  [714 238  33]
  [212 158  26]
  [ 46 280  26]
  [696 354  38]
  [156 308  16]
  [104  52  23]
  [400 454  21]
  [ 70 402  17]
  [846  58  21]
  [502 398  19]
  [790 280  32]
  [812 148  47]
  [380 134  14]
  [660 116  11]
  [592 460  32]
  [254 322  17]
  [962 532  14]
  [940 586  23]
  [946 268  11]
  [ 46  28  42]
  [540  12  22]
  [306 280  19]
  [754  70  12]
  [750 534  48]
  [306 338  35]
  [960  46  14]
  [148  18  12]
  [154  76   9]
  [478 502  25]
  [620 518  34]
  [754 150  24]
  [554 380   9]
  [668  66  12]
  [694 302  14]
  [186 412   8]
  [408 324  13]]]
(622, 984)
